// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1llYjvNkxsxABZ4G14TFfsSrkZ7AAhbE',
    appId: '1:308416020714:web:349137fb7d695f32111793',
    messagingSenderId: '308416020714',
    projectId: 'skillup-59422',
    authDomain: 'skillup-59422.firebaseapp.com',
    storageBucket: 'skillup-59422.firebasestorage.app',
    measurementId: 'G-SF3NQYJHZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjNQ1RQq3rIL3melnI2SNaw8HqEKhRz3s',
    appId: '1:308416020714:android:027b03cc71157d6c111793',
    messagingSenderId: '308416020714',
    projectId: 'skillup-59422',
    storageBucket: 'skillup-59422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNg8mNdOV8NxAb6f5vIc6KnOauRJfw5kQ',
    appId: '1:308416020714:ios:1975dafda411b187111793',
    messagingSenderId: '308416020714',
    projectId: 'skillup-59422',
    storageBucket: 'skillup-59422.firebasestorage.app',
    iosBundleId: 'com.example.finaproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNg8mNdOV8NxAb6f5vIc6KnOauRJfw5kQ',
    appId: '1:308416020714:ios:1975dafda411b187111793',
    messagingSenderId: '308416020714',
    projectId: 'skillup-59422',
    storageBucket: 'skillup-59422.firebasestorage.app',
    iosBundleId: 'com.example.finaproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1llYjvNkxsxABZ4G14TFfsSrkZ7AAhbE',
    appId: '1:308416020714:web:227234f87e093efc111793',
    messagingSenderId: '308416020714',
    projectId: 'skillup-59422',
    authDomain: 'skillup-59422.firebaseapp.com',
    storageBucket: 'skillup-59422.firebasestorage.app',
    measurementId: 'G-MLSGLWMQJQ',
  );

}